server:
  port: 9089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mycms?characterEncoding=UTF-8
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
    continueOnError: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect